### ISSUE TITLE
Hi, I want to achieve binance exchange support, how do I do it? 

### ISSUE THREAD

**Issue by bs32g1038** [SockTrader/SockTrader#71]

**Comment by cwouter** [comment]
Hi @bs32g1038 we're currently working on SockTrader 2.0 on a closed source repo. We're planning to release a beta version (as open source) within the next couple weeks / months. Note that SockTrader 2.0 has built-in support for Binance as well as several other improvements. For now I would recommend you to wait for SockTrader 2.0

**Comment by bs32g1038** [comment]
Thank you for your hard work.

**Comment by bs32g1038** [comment]
@cwouter Do you need my help? I thought I could help you speed up your project.

**Comment by cwouter** [comment]
@bs32g1038 thanks for the interest, I really appreciate that! Can you contact me on telegram? Or do you prefer a different channel?

**Comment by cwouter** [comment]
@bs32g1038 my telegram alias is @ cwouter

**Comment by cwouter** [comment]
@bs32g1038 SockTrader 2 (with binance support) is available on a separate branch: https://github.com/SockTrader/SockTrader/tree/socktrader-v2. Please note, v2 is still under construction with possibly breaking api changes and not fully production tested just yet. However, don't let this hold you back from experimenting or contributing.

If you need any assistance you can either open a new issue, or contact me on telegram as "@cwouter". Feel free to open a pull request for any contribution you would like to add.

**Comment by bs32g1038** [comment]
@cwouter  Sorry for the late reply, I've been busy with the year-end work.I will keep an eye on the project.

**Comment by cwouter** [comment]
@bs32g1038 good luck with your year-end work! ;-)
