### ISSUE TITLE
Trade decimal quantities of assets

### ISSUE THREAD

**Issue by thijs-raets** [SockTrader/SockTrader#9]
### Context
In JavaScript some floating point rounding issues might occur after applying arithmetic operations on numbers. More information can be found [here](https://hackernoon.com/understanding-the-problem-javascript-maths-2119d85dad2a) and [here](https://modernweb.com/what-every-javascript-developer-should-know-about-floating-points/)

This might prevents us from trading accurate decimal quantities in SockTrader.
Possible libraries:
- https://github.com/MikeMcl/bignumber.js/
- https://github.com/MikeMcl/big.js
- https://github.com/MikeMcl/decimal.js/

### Acceptance criteria

- calculation logic in wallet and analyzers use library for correct decimal handling
- add unit testing to prove that no rounding issues occur

**Comment by cwouter** [comment]
It might be better to start off with unit testing. This might give us some more information about the impact.

**Comment by cwouter** [comment]
this issue currently occurs on the [update-wallet-paper-trading](https://github.com/SockTrader/SockTrader/tree/update-wallet-paper-trading) branch. It can be reproduced by logging the assets in the [updateAssets function](https://github.com/SockTrader/SockTrader/blob/a56347af97deec2604742d7e2313c4e39a87dc3f/src/sockTrader/core/assets/wallet.ts#L138) of the wallet
